In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

numpy_version = np.__version__
print(f"NumPy Version: {numpy_version}")

np.show_config()


NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4499572816
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26

In [47]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))
print(a)

[[[7.43751969e-02 1.48060727e-01 2.75902757e-01 9.75984382e-01
   8.89038694e-01]
  [2.59316704e-04 4.17283929e-01 8.17379195e-01 8.01631460e-01
   8.69528236e-01]
  [1.56621328e-01 8.58201862e-01 4.69852721e-01 8.15149575e-01
   3.15617130e-01]]

 [[5.72127735e-01 2.87736258e-01 8.11102209e-01 4.37388836e-02
   2.26052715e-01]
  [5.94324159e-01 3.27864756e-01 1.11123069e-01 1.59178017e-01
   1.63913241e-01]
  [6.95890011e-01 9.38033086e-01 1.66622294e-01 3.88848374e-01
   4.66066410e-02]]]


In [48]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

# Print the array
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?

same_size = a.size == b.size
print(same_size)

True


In [49]:
combine = a + b
print(combine)

#not possible. not same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [50]:
c = b.reshape(2, 3, 5)
print(c)







[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [51]:
d = np.add(a, c)
print(d)

[[[1.0743752  1.14806073 1.27590276 1.97598438 1.88903869]
  [1.00025932 1.41728393 1.8173792  1.80163146 1.86952824]
  [1.15662133 1.85820186 1.46985272 1.81514957 1.31561713]]

 [[1.57212773 1.28773626 1.81110221 1.04373888 1.22605271]
  [1.59432416 1.32786476 1.11112307 1.15917802 1.16391324]
  [1.69589001 1.93803309 1.16662229 1.38884837 1.04660664]]]


In [52]:
e = np.multiply (a, c)
print(e)

[[[7.43751969e-02 1.48060727e-01 2.75902757e-01 9.75984382e-01
   8.89038694e-01]
  [2.59316704e-04 4.17283929e-01 8.17379195e-01 8.01631460e-01
   8.69528236e-01]
  [1.56621328e-01 8.58201862e-01 4.69852721e-01 8.15149575e-01
   3.15617130e-01]]

 [[5.72127735e-01 2.87736258e-01 8.11102209e-01 4.37388836e-02
   2.26052715e-01]
  [5.94324159e-01 3.27864756e-01 1.11123069e-01 1.59178017e-01
   1.63913241e-01]
  [6.95890011e-01 9.38033086e-01 1.66622294e-01 3.88848374e-01
   4.66066410e-02]]]


In [56]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9759843821838883 1.000259316703878 1.4472682652737874


In [57]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty_like(d)
print(f)
print(d)


[[[1.0743752  1.14806073 1.27590276 1.97598438 1.88903869]
  [1.00025932 1.41728393 1.8173792  1.80163146 1.86952824]
  [1.15662133 1.85820186 1.46985272 1.81514957 1.31561713]]

 [[1.57212773 1.28773626 1.81110221 1.04373888 1.22605271]
  [1.59432416 1.32786476 1.11112307 1.15917802 1.16391324]
  [1.69589001 1.93803309 1.16662229 1.38884837 1.04660664]]]
[[[1.0743752  1.14806073 1.27590276 1.97598438 1.88903869]
  [1.00025932 1.41728393 1.8173792  1.80163146 1.86952824]
  [1.15662133 1.85820186 1.46985272 1.81514957 1.31561713]]

 [[1.57212773 1.28773626 1.81110221 1.04373888 1.22605271]
  [1.59432416 1.32786476 1.11112307 1.15917802 1.16391324]
  [1.69589001 1.93803309 1.16662229 1.38884837 1.04660664]]]


In [58]:
f[(d > d_min)  & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)
print(d)

[[[ 25.  25.  25. 100.  75.]
  [  0.  25.  75.  75.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.  25.]]]
[[[1.0743752  1.14806073 1.27590276 1.97598438 1.88903869]
  [1.00025932 1.41728393 1.8173792  1.80163146 1.86952824]
  [1.15662133 1.85820186 1.46985272 1.81514957 1.31561713]]

 [[1.57212773 1.28773626 1.81110221 1.04373888 1.22605271]
  [1.59432416 1.32786476 1.11112307 1.15917802 1.16391324]
  [1.69589001 1.93803309 1.16662229 1.38884837 1.04660664]]]
